sonar.projectKey=StarPivot-frontend
sonar.projectName=StarPivot Frontend
sonar.projectVersion=3.0.1

sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/.cursor/**,**/public/**,**/assets/**,**/*.spec.ts,**/*.test.ts

sonar.tests=src
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts
sonar.test.exclusions=**/node_modules/**,**/dist/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json

sonar.eslint.reportPaths=eslint-report.json

sonar.qualitygate.wait=true

sonar.coverage.exclusions=**/*.vue,**/types/**,**/api/**,**/router/**,**/store/**

sonar.issue.ignore.multicriteria=e1,e2,e3
sonar.issue.ignore.multicriteria.e1.ruleKey=typescript:S1135
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.ts
sonar.issue.ignore.multicriteria.e2.ruleKey=typescript:S3776
sonar.issue.ignore.multicriteria.e2.resourceKey=**/*.ts
sonar.issue.ignore.multicriteria.e3.ruleKey=typescript:S1066
sonar.issue.ignore.multicriteria.e3.resourceKey=**/*.ts
