sonar.projectKey=StarPivot
sonar.projectName=StarPivot
sonar.projectVersion=0.0.1-SNAPSHOT

sonar.sourceEncoding=UTF-8

sonar.sources=star-pivot-controller/src,star-pivot-framework/src,star-pivot-module/src
sonar.tests=star-pivot-module/src/test
sonar.java.source=17
sonar.java.target=17

sonar.java.binaries=star-pivot-controller/target/classes,star-pivot-module/*/target/classes
sonar.java.test.binaries=star-pivot-module/*/target/test-classes

sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.junit.reportsPath=target/surefire-reports

sonar.exclusions=**/target/**,**/node_modules/**,**/*.md,**/*.txt

sonar.java.codeCoveragePlugin=jacoco
sonar.coverage.exclusions=**/*DTO.java,**/*VO.java,**/config/**,**/domain/**,**/entity/**

sonar.issue.ignore.multicriteria=e1,e2
sonar.issue.ignore.multicriteria.e1.ruleKey=java:S100
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.java
sonar.issue.ignore.multicriteria.e2.ruleKey=java:S117
sonar.issue.ignore.multicriteria.e2.resourceKey=**/*.java

sonar.qualitygate.wait=true
